"""service soft delete

Revision ID: b730ecb35598
Revises: 41f87c615a7c
Create Date: 2026-07-12 09:54:25.051448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b730ecb35598'
down_revision: Union[str, Sequence[str], None] = '41f87c615a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default so existing rows (populated before this column existed)
    # backfill to true instead of violating the NOT NULL constraint.
    op.add_column(
        'service',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'is_active')
    # ### end Alembic commands ###
